export const projects = [
    {
        id: "01",
        title: "E-commerce product page",
        description: "A single product page with a lightbox product gallery and cart functionality.",
        skills: ["React JS", "CSS", "BEM", "HTML"],
        site: "https://ledesmx.github.io/ecommerce-product-page/",
        code: "https://github.com/ledesmx/ecommerce-product-page",
        img: "./project-01-preview.jpg",
        color: "coral",
    },
    {
        id: "02",
        title: "URL shortening landing page",
        description: "A URL shortening page that utilizes API and local storage to store the shortened URLs.",
        skills: ["React JS", "Tailwind CSS", "HTML"],
        site: "https://ledesmx.github.io/URL-shortening-API-landing-page/",
        code: "https://github.com/ledesmx/URL-shortening-API-landing-page",
        img: "./project-02-preview.jpg",
        color: "turquoise",
    },
    {
        id: "03",
        title: "Todo app usign Firebase",
        description: "A classic to-do app with a dark/light theme and drag-and-drop reordering built with Firebase.",
        skills: ["React JS", "Tailwind CSS", "HTML", "Firebase"],
        site: "https://ledesmx.github.io/Todo-App/",
        code: "https://github.com/ledesmx/Todo-App",
        img: "./project-03-preview.jpg",
        color: "purple",
    },
]
